### ISSUE TITLE
Warnings and Errors during npm install

### ISSUE THREAD

**Issue by Luciden** [perarnborg/vuex-oidc-example#2]
Many warnings. Here's one example:
npm WARN tar ENOENT: no such file or directory, open 'D:\Projects\oidc\vuex-oidc-example\node_modules\.staging\postcss-selector-parser-9408d90e\package.json'

Then this error:
npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2

I tried to install that but received an error

Tried to npm run serve and received:
''vue-cli-service' is not recognized as an internal or external command,'

**Comment by perarnborg** [comment]
Strange. What version of node / npm are you using? I made some dependency updates in the project, if you want you can check if it works better now after pulling down the latest code and doing `rm -r node_modules && npm i`?

**Comment by perarnborg** [comment]
@Luciden Did you look into this? Are you still experiencing problems installing the example?
