### ISSUE TITLE
Running silent renewal on remote server triggers file download

### ISSUE THREAD

**Issue by cosminstefanxp** [perarnborg/vuex-oidc-example#3]
I'm using the very nice library to implement OIDC in my Vue app and, while everything works fine on `localhost`, when deploying the app remotely (e.g. in Firebase Hosting), whenever the silent renewal succeeds, the browsers download the file at the silent sign-in url.

So, with the following config:
```
{
    authority: "https://example.com",
    client_id: "xyz",
    scope: "openid profile",
    response_type: "token id_token",
    userStore: new WebStorageStateStore({store: localStorage}),
    redirect_uri: `${appUrl}/auth/signin-success`,
    silent_redirect_uri: `${appUrl}/auth/silent-signin-success`,
    post_logout_redirect_uri: `${appUrl}/auth/signout-success`,
    automaticSilentRenew: true, 
}
```
if I force a silent renewal at app startup via: `store.dispatch("authenticateOidcSilent")`, the silent login runs in the background & makes the right network calls, but the browser (tried on both Chrome and Safari) detects the success callback as a download request and literally downloads the `silent-signin-success` instead of interpreting it.

**Comment by perarnborg** [comment]
I have not seen this before. Are the request and response headers any different in your different environmets?

Is it the request to your app’s silent_redirect_uri that the browser downloads as a file? The headers of that request sound like the first place to look for trouble.

**Comment by cosminstefanxp** [comment]
Hey. Yes, that was a good direction. The issue is not with the `vuex-oidc`, but with how Firebase serves certain resources. Since it was lacking the `.html` extension, it was serving the file as binary, so it would not be handled properly by the Browswer. Thank you.
