### ISSUE TITLE
Where is silent-renew-oidc.js referenced?

### ISSUE THREAD

**Issue by paulvanbladel** [perarnborg/vuex-oidc-example#4]
I am a bit confused how silent renew works?
Should the above mentioned file not be referenced in the silent renew html file?
Is silent renew a pure client side matter. So nothing  particular at identity server to be configured?

BTW, very nice library. Thanks a lot.

**Comment by perarnborg** [comment]
@paulvanbladel Yes the js file is referenced in the HTML file. In this example I have used the pages concept in vue cli for the silent renew callback. 
https://github.com/perarnborg/vuex-oidc-example/blob/9ae2a00fb2bfdbc43899a316f62f7fad680a0d23/vue.config.js#L13

Correct, the silent renew is done client side. Simplified, the browser makes an authentication request to the open id provider in a hidden iframe with the silent renew callback set as callback uri. So if the user is authenticated the iframe will be redirected to the silent renew callback and from there a postmessage will be performed to the parent window with fresh tokens.

**Comment by paulvanbladel** [comment]
@perarnborg many thanks.
