### ISSUE TITLE
"Promise is undefined" on IE11

### ISSUE THREAD

**Issue by mrenauld** [perarnborg/vuex-oidc-example#9]
It seems that this application does not work on IE11. I start locally with `npm run serve`, then go to `http://localhost:5002/`. On Chrome it works but on IE11 I get a blank page and in the logs:

      SCRIPT5009: 'Promise' is undefined
      oidc-client.min.js (1,14631)

The second line is a link to `webpack-internal:///node_modules/oidc-client/lib/oidc-client.min.js`.

Do you know how to make this work on IE11?

**Comment by perarnborg** [comment]
You need a Promise polyfill for this library’s dependency oidc-client to work in IE.

corejs has a good polyfill. I you use vue-cli, they have a really good implementation of @babel/preset-env which makes legacy support a breeze. See https://cli.vuejs.org/guide/browser-compatibility.html#browserslist
